import { ROLES } from './roles';

export const PERMISSIONS = {
  CREATE_COURSE: [ROLES.ADMIN, ROLES.FACULTY],
  EDIT_COURSE: [ROLES.ADMIN, ROLES.FACULTY],
  DELETE_COURSE: [ROLES.ADMIN],
  VIEW_ALL_COURSES: [ROLES.ADMIN, ROLES.FACULTY, ROLES.STUDENT],
  CREATE_ASSIGNMENT: [ROLES.FACULTY],
  GRADE_ASSIGNMENT: [ROLES.FACULTY],
  SUBMIT_ASSIGNMENT: [ROLES.STUDENT],
  MANAGE_USERS: [ROLES.ADMIN],
  VIEW_ANALYTICS: [ROLES.ADMIN],
  MARK_ATTENDANCE: [ROLES.FACULTY],
  VIEW_GRADES: [ROLES.ADMIN, ROLES.FACULTY, ROLES.STUDENT],
  ENROLL_COURSE: [ROLES.STUDENT]
};

export const hasPermission = (userRole, permission) => {
  return PERMISSIONS[permission]?.includes(userRole) || false;
};
